version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build-and-test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:22.12.0
      - image: postgres:15
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testapp
    environment:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/testapp
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
